# Generated by Django 5.2.7 on 2025-10-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('lr', 'Logistic Regression'), ('svm', 'Support Vector Machine'), ('nb', 'Naive Bayes'), ('rf', 'Random Forest')], max_length=200)),
                ('input_text', models.CharField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
